name: Bug Report
description: Something isn't working
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: Thank you for taking the time to fill out this bug report!

  - type: input
    attributes:
      label: Module Name
      description: Which module are you experiencing issues with?
      placeholder: storage

  - type: input
    attributes:
      label: Module Version
      description: Which module version are you using?
      placeholder: 1.0.0

  - type: input
    attributes:
      label: Terraform Version
      description: Which Terraform version are you using?
      placeholder: 1.0.0

  - type: input
    attributes:
      label: Description
      description: Please describe the issue you are experiencing.

  - type: input
    attributes:
      label: Example Terraform Configuration
      description: Please provide an example Terraform configuration that can reproduce the issue.

  - type: input
    attributes:
      label: Steps to Reproduce
      description: Please provide the steps required to reproduce the issue.
