name: ci

on:
  push:
    branches: [main]
    paths:
      - docs/**
      - mkdocs.yml

jobs:
  build:
    name: Build
    uses: equinor/ops-actions/.github/workflows/mkdocs.yml@v9.12.4
    with:
      python_version: 3.12.0
      requirements: requirements.txt

  deploy:
    name: Deploy
    needs: build
    uses: equinor/ops-actions/.github/workflows/github-pages.yml@v9.12.4
    with:
      artifact_name: ${{ needs.build.outputs.artifact_name }}
