name: Terraform Test

on:
  workflow_call:
    inputs:
      test-filter:
        description: Limit the Terraform Test operation to the specified test files.
        type: string
        required: false

jobs:
  terraform-test:
    name: Terraform Test
    runs-on: ubuntu-latest
    env:
      TF_IN_AUTOMATION: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest
          terraform_wrapper: false

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform Test
        id: test
        env:
          TF_TEST_FILTER: ${{ inputs.test-filter }}
        run: terraform test -filter="$TF_TEST_FILTER"
